// apps/web/src/lib/components/chat/Composer.tsx
import type { SelectableModel } from '@house-elf/shared';
import type { ChatStatus } from 'ai';
import type { ChangeEvent } from 'react';
import { useState } from 'react';

import { chatStatus } from '../../constants/chat-status.ts';
import {
	PromptInput,
	PromptInputBody,
	PromptInputFooter,
	PromptInputSubmit,
	PromptInputTextarea,
	PromptInputTools,
	type PromptInputMessage
} from '../vendor/ai-elements/prompt-input.tsx';
import { ModelPicker } from './ModelPicker.tsx';

export interface ComposerProps {
	status: ChatStatus;
	onSend: (text: string) => void;
	onStop: () => void;
	models: readonly SelectableModel[];
	selectedModelId: string;
	onModelSelect: (modelId: string) => void;
	thinking: boolean;
	canChooseThinking: boolean;
	onThinkingChange: (thinking: boolean) => void;
}

export function Composer({
	status,
	onSend,
	onStop,
	models,
	selectedModelId,
	onModelSelect,
	thinking,
	canChooseThinking,
	onThinkingChange
}: ComposerProps) {
	const [draft, setDraft] = useState('');

	// `submitted` covers the gap between sending and the first chunk, when there is
	// nothing on screen yet but the request is already in flight.
	const busy = status === chatStatus.submitted || status === chatStatus.streaming;
	const canSend = draft.trim().length > 0 && !busy;

	function handleSubmit(message: PromptInputMessage) {
		// PromptInputTextarea's own Enter handler falls back to
		// `form.requestSubmit()` whenever it can't find a `button[type="submit"]`
		// to check for `disabled` — which is exactly the case while busy, since
		// PromptInputSubmit swaps to `type="button"` for Stop. This is the one
		// path the vendor's own empty-text disabled-check on the submit button
		// doesn't cover, so it's guarded here instead. Everything else — the IME
		// double-check, the Shift+Enter split, and the empty-text guard on both
		// Enter and click — is the vendored behaviour, unmodified.
		if (!canSend) {
			return;
		}

		onSend(message.text);
		setDraft('');
	}

	function handleChange(event: ChangeEvent<HTMLTextAreaElement>) {
		setDraft(event.target.value);
	}

	return (
		// The border spans the full width of this bar; only the input itself is
		// centered and width-capped, matching the original Svelte layout. Both
		// classes on one element would clip the border to the capped width instead.
		<div className="border-t border-border px-4 py-3">
			<PromptInput className="mx-auto max-w-3xl" onSubmit={handleSubmit}>
				<PromptInputBody>
					<PromptInputTextarea
						aria-label="Message"
						onChange={handleChange}
						placeholder="Send a message…"
						value={draft}
					/>
				</PromptInputBody>

				<PromptInputFooter>
					<PromptInputTools>
						<ModelPicker
							canChooseThinking={canChooseThinking}
							models={models}
							onSelect={onModelSelect}
							onThinkingChange={onThinkingChange}
							selectedModelId={selectedModelId}
							thinking={thinking}
						/>
					</PromptInputTools>

					<PromptInputSubmit disabled={!busy && !canSend} onStop={onStop} status={status} />
				</PromptInputFooter>
			</PromptInput>
		</div>
	);
}

// apps/web/src/lib/components/chat/Composer.svelte
<script lang="ts">
	import type { SelectableModel } from '@house-elf/shared';
	import type { ChatStatus } from 'ai';

	import ModelPicker from './ModelPicker.svelte';

	interface ComposerProps {
		status: ChatStatus;
		onsend: (text: string) => void;
		onstop: () => void;
		models: readonly SelectableModel[];
		selectedModelId: string;
		onmodelselect: (modelId: string) => void;
		thinking: boolean;
		canChooseThinking: boolean;
		onthinkingchange: (thinking: boolean) => void;
	}

	let {
		status,
		onsend,
		onstop,
		models,
		selectedModelId,
		onmodelselect,
		thinking,
		canChooseThinking,
		onthinkingchange
	}: ComposerProps = $props();

	let text = $state('');

	// `submitted` covers the gap between sending and the first chunk, when there is
	// nothing on screen yet but the request is already in flight.
	const busy = $derived(status === 'submitted' || status === 'streaming');
	const canSend = $derived(text.trim().length > 0 && !busy);

	// Tracked as well as read from the event, because `KeyboardEvent.isComposing`
	// is not reliable across browsers — some report `false` for the Enter that
	// accepts an IME candidate. Getting this wrong sends half-composed Japanese or
	// Chinese, so both signals are checked and either one is enough to bail out.
	let composing = $state(false);

	function send() {
		if (!canSend) return;
		onsend(text);
		text = '';
	}

	function onkeydown(event: KeyboardEvent) {
		// Shift+Enter inserts a newline, so it must fall through to the textarea.
		if (event.key !== 'Enter' || event.shiftKey || event.isComposing || composing) return;

		event.preventDefault();
		send();
	}

	function onsubmit(event: SubmitEvent) {
		event.preventDefault();
		send();
	}

	function oncompositionstart() {
		composing = true;
	}

	function oncompositionend() {
		composing = false;
	}
</script>

<form class="border-t border-line bg-canvas px-4 py-3" {onsubmit}>
	<div class="mx-auto max-w-3xl overflow-hidden rounded-xl border border-line bg-raised">
		<textarea
			bind:value={text}
			{onkeydown}
			{oncompositionstart}
			{oncompositionend}
			rows="1"
			placeholder="Send a message…"
			aria-label="Message"
			class="max-h-48 min-h-12 w-full resize-none bg-transparent px-3 pt-3 pb-2 text-sm outline-none placeholder:text-faint"
		></textarea>

		<div class="flex items-center justify-end gap-1.5 px-2 pb-2">
			<ModelPicker
				{models}
				{selectedModelId}
				onselect={onmodelselect}
				{thinking}
				{canChooseThinking}
				{onthinkingchange}
			/>

			{#if busy}
				<button
					type="button"
					onclick={onstop}
					class="flex h-8 shrink-0 items-center gap-2 rounded-md border border-line px-3 text-xs text-muted transition-colors hover:bg-canvas hover:text-content"
				>
					<!-- The only sign anything is happening between pressing Enter and the
					     first token arriving: pulsing while the request is in flight, steady
					     once the reply is actually coming. The label stays "Stop" in both
					     states, because that is what the button does. -->
					<span
						class="size-1.5 rounded-full bg-accent"
						class:animate-pulse={status === 'submitted'}
						aria-hidden="true"
					></span>
					Stop
				</button>
			{:else}
				<button
					type="submit"
					disabled={!canSend}
					class="h-8 shrink-0 rounded-md bg-accent px-3 text-xs font-medium text-canvas transition-opacity disabled:opacity-40"
				>
					Send
				</button>
			{/if}
		</div>
	</div>
</form>
