// apps/web/src/routes/c/new/+page.svelte
<script lang="ts">
	import ChatView from '$lib/components/chat/ChatView.svelte';

	import type { PageProps } from './$types';

	let { data }: PageProps = $props();
</script>

<!-- One agent for now. M3 adds the picker; the route already carries the id. -->
<ChatView agentId="general" modelCatalog={data.modelCatalog} />

// apps/web-react/src/routes/c/new.tsx
import { createFileRoute } from '@tanstack/react-router';

import { ChatView } from '../../lib/components/chat/ChatView.tsx';
import { getModelCatalog } from '../../lib/server/model-catalog.functions.ts';

export const Route = createFileRoute('/c/new')({
	loader: async () => ({ modelCatalog: await getModelCatalog() }),
	component: NewConversationPage
});

function NewConversationPage() {
	const { modelCatalog } = Route.useLoaderData();

	return (
		<div className="h-full min-h-0">
			<ChatView agentId="general" modelCatalog={modelCatalog} />
		</div>
	);
}
